name: Deploy Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    environment: production

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Generate config
        env:
          API_URL: ${{ secrets.API_KEY }}
        run: |
          cat > config.js <<EOF
          window.CONFIG = {
            apiUrl: "$API_KEY"
          };
          EOF

      - uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - uses: actions/deploy-pages@v4
